name: ci
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy-to-netcup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          run_install: true
      - name: Build app
        run: npm run docs:build
      - name: copy files via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_BLOG_PATH }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "./blog/.vitepress/dist/*"
          target: "./httpdocs/"
          strip_components: 1
